- chaos/db_helper.py
- chaos/models.py
- migrations/versions/2cd4af730af5_.py
- tests/features/update-impact.feature
This PR add version to the impact table and increment this value for each submit of traffic report form
This modification update the update_at column, too
This is an enhancement
http://jira.canaltp.fr/browse/TR-785
> Feature tr 785 update date impact connector ogv1

- chaos/publisher.py
We have a lot of socket errors when sending disruption to chaos. This fix seems to solve the problem.
> api: ensure 3 retries before failure when sending messages to rabbitmq

- PULL_REQUEST_TEMPLATE
> Template for PR

- chaos/models.py
- chaos/populate_pb.py
- chaos/resources.py
- chaos/utils.py
- tests/disruption_test.py
This PR fixes error when we delect a disruption and we do not push this delection to rabbitmq
http://jira.canaltp.fr/browse/RZO-61
> remove is_published check

- chaos/models.py
This PR fixes comment from PR https://github.com/CanalTP/Chaos/pull/206
-> https://github.com/CanalTP/Chaos/pull/206#discussion_r86728153
> Add delete cascade to disruption table

- chaos/models.py
- tests/features/list-disruption-with-tag.feature
- tests/features/list-disruptions-filtrer-publication_statuspager.feature
- tests/features/list-disruptions-with-current-time.feature
- tests/features/list-disruptions.feature
JIRA:
http://jira.canaltp.fr/browse/RZO-334
> RZO-334 order get disruptions by end publication date desc

- chaos/__init__.py
This PR rollbacks without PR #209
> fix version number and rollback PR #209

- chaos/resources.py
This PR improves logging in POST /disruptions
Issue link: http://jira.canaltp.fr/browse/RZO-332
Create a disruption with unknown ptObject for example
> display headers, payload of request and response in case of error

- chaos/resources.py
This PR change logging format for POST and PUT disruptions
To get a 400 on local env: 
```
curl -i -X POST \
-H "X-Coverage:transilien" \
-H "X-Contributors:shortterm.tr_tra" \
-H "Authorization:d867e37e-7078-40ca-9763-efec48e86660" \
-H "X-Customer-Id:trans" \
-H "Content-Type:application/json" \
-d \
'{
"reference": "PCI Event from Perturbation_Chaos_25154 - n°131495"
}' \
'http://localhost:5000/disruptions'
```
> add status code and implode log line

- chaos/__init__.py
This PR fixes an incompatibility with NewRelic agent. This incompatibility is due to gevent monkey patching on threads.
Hence... we do not monkey patch threads any more
This is a compliance fix
- with a new relic agent configured in wsgi, you should be able to see data in NewRelic
@kinnou02 @CanalTP/transteam
> Do not monkey patch threads to be NewRelic-compliant

- documentation/disruptions.md
- documentation/disruptions_fr.md
This PR update documentation
Issue link: RZO-461
> Documentation cause wording

- tests/features/steps.py
- tests/features/traffic_reports.feature
This PR fixes/adds ...
Issue link:
This is a bug fix / new feature?
- step 1
- step 2
- ...
> chaos: Modification to test existance of an object in a list

- documentation/disruptions.md
- documentation/disruptions_fr.md
This PR adds an attribut notification_date in an impact in the doc
Issue link:
This is a bug fix / new feature?
No test needed
> chaos: Attribut notification_date added in an impact.

- chaos/db_helper.py
- chaos/fields.py
- chaos/formats.py
- chaos/models.py
- chaos/populate_pb.py
- migrations/versions/e33962db5d9_.py
- tests/features/disruption-with-impacts.feature
- tests/features/impacts-with-application_period_patterns.feature
- tests/format_test.py
- tests/populate_pb_test.py
This PR adds an attribut notification_date in the impact
This is a new feature:
http://jira.canaltp.fr/browse/BOT-16
> chaos: attribut notification_date added in the impact

- documentation/disruptions.md
This PR is just an update for some details in the documentation.
> documentation update

- README.md
This PR adds recent Cache information
Read it :books:
> Documentation Cache info

- chaos/exceptions.py
- chaos/navitia.py
- requirements.txt
- tests/navitia_test.py
This PR fixes some Navitia timeout calls
http://jira.canaltp.fr/browse/BOT-33
Checkout for disappearance of timeout errors in error.log
> Retrying Navitia calls if Timeout

- .gitignore
- README.md
- chaos/resources.py
- tests/features/deletion-disruption.feature
lettuce tests pass, did not run unit tests.
> Clarify readme on protoc install and require client id when deleting a disruption.

- chaos/populate_pb.py
- tests/populate_pb_test.py
This PR fixes error on severity.priority
Ticket concerned: https://jira.canaltp.fr/browse/NAVITIAII-2229
> chaos: publish priority value in severity

- documentation/disruptions.md
This PR fixes documentation error about PUT impact
Issue link: BOT-24
- read it
(and eventually check a PUT)
> Resolution Documentation PUT impact

- documentation/disruptions.md
This PR update some display in the doc
Issue link: BOT-37, BOT-24
> Update display /order in the doc

- README.md
- requirements.txt
This PR is required to get 'CACHE_OPTIONS': {'socket_timeout': 0.1 }, working 
https://github.com/CanalTP/fab_chaos/pull/17
Issue link: BOT-262
just use it, no usage modification
> Requirement werkzeug up

- chaos/populate_pb.py
- tests/populate_pb_test.py
This PR adds disruption properties in populate_pb in order to send them to navitia.
https://github.com/CanalTP/navitia/pull/2257
feature
as usual
> Pr disruption properties

- Dockerfile
- Dockerfile.dev
- docker/run.sh
This PR fix the error when trying to install via pip with docker
Issue link: BOT-318
> Fix pip install fail

- README.md
This PR adds security section to README file
Issue link: BOT-386
> Updating Chaos documentation with information about securization

- documentation/swagger.yml
This update swagger documentation for cause section
> Refs #BOT-441 ~ cause section updated.

- documentation/swagger.yml
This update swagger documentation for property section
> Refs 441 update swagger documentation property

- documentation/swagger.yml
This update swagger documentation for tag section
> Refs #BOT-441 ~ tag section updated.

- documentation/swagger.yml
This update swagger documentation for cause section
> Refs #BOT-441 ~ severity section updated.

- documentation/swagger.yml
This update swagger documentation for channels and channel_types sections
> update swagger doc for channels and channel_types

- documentation/swagger.yml
This update swagger documentation for category disruption
> Refs 441 update swagger documentation disruption

- chaos/utils.py
> Fix pylint on chaos/utils.py

- chaos/navitia.py
> Fix pylint on chaos/navitia.py

- chaos/api.py
- chaos/cache.py
- chaos/db_helper.py
- chaos/default_settings.py
- chaos/exceptions.py
- chaos/fields.py
- chaos/formats.py
- chaos/models.py.bkp
- chaos/navitia.py
- chaos/populate_pb.py
- chaos/publisher.py
- chaos/resources.py
- chaos/utils.py
- chaos/validate_params.py
> fix some pylint errors.

- chaos/utils.py
- chaos/validate_params.py
This PR use absolute path to load client tokens. If file doesn't exist an warning log will be created
> Feature using absolute path for client tokens

- tests/navitia_test.py
- tests/testing_settings.py
This PR check if tests are correctly done if the cache is set as 'simple' because if not, there is a lot of 'status' call on navitia
Link : BOT-549
> Try to set simple cache on test

- chaos/api.py
- chaos/formats.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- tests/features/list-disruptions-filter-post.feature
- tests/features/list-disruptions-search-post.feature
- tests/features/steps.py
This PR implement filter of disruption by POST request
All parameters for GET `/disruptions` should work with POST `/disruptions/_search` by body
New parameter should work `ptObjectFilter`
More information in the new swagger: [Chaos Swagger](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/feature-BOT-534-disruptions-filter/documentation/swagger.yml)
> Feature bot 534 disruptions filter

- README.md
- chaos/utils.py
- tests/fixtures/clients_tokens.json
- tests/utils_test.py
This PR add 'master' key to do request for all client
- Add `master` key in `chaos/clients_codes.json` 
- If you use token of master you should not have `401 response`
> This PR add 'master' key to do request for all client

- README.md
- chaos/utils.py
- tests/fixtures/clients_tokens.json
- tests/utils_test.py
This PR add 'master' key to do request for all client
- Add `master` key in `chaos/clients_codes.json` 
- If you use token of master you should not have `401 response`
> Refs #BOT-558 ~ This PR add 'master' key to do request for all client

- chaos/models.py
This PR uses event 'checkout' to set UTC as timezone
Issue link: https://github.com/CanalTP/kirin/pull/136
Concerned ticket:  https://jira.kisio.org/browse/NAVP-856
@kinnou02 @xlqian
> Using event checkout to set UTC as timezone.

- documentation/swagger.yml
This PR fixes/adds ...
Issue link:
This is a bug fix / new feature?
- step 1
- step 2
- ...
> doc : DELETE archive the disruption and its impacts.

- chaos/populate_pb.py
- tests/populate_pb_test.py
also refacto the method to use helper provided by protobuf
This PR fixes https://jira.kisio.org/browse/NAVITIAII-2489
- create a new disruption with a title
- check in navitia than the channel type is to title and not unkwnow_type
> add beacon and title to channel type handled by populate_pb

- documentation/swagger.yml
This PR fixes les errors dans le documentation swagger
Issue link: BOT-514
> Update doc swagger chaos

- chaos/db_helper.py
- chaos/fields.py
- chaos/formats.py
- chaos/mapper.py
- chaos/models.py
- chaos/populate_pb.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/versions/548314a1e5ea_add_meta.py
- tests/features/impacts-with-message-meta.feature
- tests/features/steps.py
- tests/format_test.py
- tests/populate_pb_test.py
This PR add a meta entry on a message of an impact
[Swagger documentation](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-820-add-meta-to-message/documentation/swagger.yml)
Issue link: BOT-820
> Add meta entry to message

- chaos/db_helper.py
Fix for PR https://github.com/CanalTP/Chaos/pull/310
-> change function name from remove_meta to delete_meta
> Fix delete meta

- documentation/swagger.yml
This PR add a description to the required parameter in POST /channel.
> Doc : Description of Required in POST channel

- chaos/formats.py
- documentation/swagger.yml
- tests/features/create-disruption-with-impacts.feature
- tests/features/create-disruption-with-properties.feature
- tests/features/create-disruption.feature
- tests/features/update-disruption-with-impacts.feature
- tests/features/update-disruption-with-properties.feature
- tests/features/update-disruption.feature
- tests/format_test.py
This PR make publication_period required
Doc update : http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/feature-bot-692-make-publication_period-required/documentation/swagger.yml
Issue link: BOT-692
> Make publication_period required

- requirements.txt
This PR fix the security alert CVE-2018-18074
> vulnerability CVE-2018-18074

- requirements.txt
This PR fix the alert for flask vulnerability
https://github.com/CanalTP/Chaos/issues/321
BOT-966
Blocked by
https://github.com/CanalTP/flask-restful/pull/2
> Fix vulnerability CVE-2018-1000656

- chaos/models.py
- chaos/resources.py
- tests/features/deletion-impact.feature
This PR delete the disruption if the deleted impact is the last one of the disruption
Issue link: BOT-971
> Archive (delete) Disruption if archive (delete) last impact

- chaos/formats.py
- chaos/models.py
- chaos/resources.py
- chaos/utils.py
- tests/features/list-disruptions-search-post.feature
This PR add the filter on impact for application status and pt_object
Issue link: BOT-930, BOT-931
> Add filetring on impact

- chaos/formats.py
- chaos/models.py
- chaos/resources.py
- chaos/utils.py
- tests/features/list-disruptions-search-post.feature
This PR qdd application_period filter
Issue link: BOT-933
Call chaos `/disruptions/_search` with a body like :
```
{
"start_page":1,
"items_per_page":2,
"depth":2,
"line_section":"true",
"application_period": {
"begin": "2019-01-02T00:00:00Z",
"end": "2019-01-08T23:59:59Z"
}
}
```
> Add application_period filter

- chaos/resources.py
- tests/features/list-disruptions-search-post.feature
This PR fixes the order of POST disruption _search
> Bug correction for POST disruption _search

- chaos/models.py
This PR removes code duplication for native query in disruptions/_search API
Issue link: BOT-1046
This is a technical debt
> Refactor disruption search native query

- chaos/navitia.py
This PR fix tme out errot  with redis.
Now we call navitia if we have it.
> Refs BOT-1156 ~ Now we check if redis response timeout.

- chaos/publisher.py
This PR adds callback called each time the connection can’t be established and log infos in logger.
Issue link: BOT-1166
- Create new impact (you can use IHM TR) while restarting rabbitmq-server
- You should see "Retry in x seconds." in logger
> Improve logs - Add retry infos in logger

- documentation/swagger.yml
This PR add impacts_search in swagger
Issue link: bot-1163
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-1163-doc-swagger-POST-impact-search/documentation/swagger.yml#/Search/post_impacts__search
> Add impacts_search in swagger

- tests/features/post-impacts-search.feature
This PR implemente tests for `/impacts/_search`
> Refs #BOT-1164 ~ Some tests added for /impacts/_search.

- chaos/api.py
- chaos/fields.py
- chaos/formats.py
- chaos/models.py
- chaos/resources.py
- chaos/utils.py
This PR add impacts search
Issue link: BOT-1098
> Add impacts search

- chaos/api.py
- chaos/fields.py
- chaos/formats.py
- chaos/models.py
- chaos/resources.py
- chaos/utils.py
- documentation/swagger.yml
- tests/features/post-impacts-search.feature
This PR adds POST impacts/_search
Issue link: BOT-1098
> POST impacts/_search

- chaos/resources.py
- chaos/utils.py
- chaos/validate_params.py
- tests/features/create-disruption-with-impacts.feature
This PR fix the pb with external bot / ihm who doesn't send `notification_date` when they send `send_notifications=True`
Issue link: BOT-1260
> Update notification date in certain case

- documentation/swagger.yml
- migrations/versions/bf4581a9122_create_export_table.py
This PR add doc swagger and migration for export archive
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-1267-swagger-migration/documentation/swagger.yml#/
Issue link: BOT-1267
> Add doc swagger and migration for export archive

- chaos/fields.py
- chaos/formats.py
- chaos/mapper.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- tests/features/create-export.feature
This PR implement POST `/impacts/exports` route
Issue link: https://jira.kisio.org/browse/BOT-1268
> Task bot 1268 post export

- chaos/fields.py
- chaos/mapper.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/versions/bf4581a9122_create_export_table.py
- tests/features/create-export.feature
- tests/features/list-export.feature
This PR add the time_zone in order to create correctly the export (with correct datetime)
Issue link: BOT-1268 BOT-854
> Add timezone into API export

- chaos/default_settings.py
- chaos/resources.py
- impactsExporter.py
This PR fix the problem of the python venv (for plateform release) and some config
:warning: This PR need https://github.com/CanalTP/fab_chaos/pull/36 for the release on plateform
> Task bot 1271 worker export fix venv

- requirements.txt
> Update requirements.txt for Jinja2

- migrations/versions/cf4581a9123_init_history_schema.py
- tests/features/terrain.py
This PR add misgration script to init the history of disruption
Issue link: BOT-1316
> Migration script for history

- documentation/swagger.yml
This PR adds documentation about get impacts history
Issue link: bot-1338
just read it :eyeglasses:
> Doc. impacts in history

- documentation/swagger.yml
This PR  sort  definitions order alphabetically
Just read it
> Doc swagger definitions sorted

- migrations/versions/50f90e14e248_history_disruptions.py
This PR add history migration file
Issue link: bot-1383
> Add history migration file

- chaos/history.py
This PR handles technical debt on disruption history API
> [History] Refacto task bot 1384 tech debt

- chaos/models.py
- chaos/resources.py
- tests/features/list-disruption-with-impacts-history.feature
This PR adds History enrichment when actions on impacts
Issue link: BOT-1385
- create then modify some disruptions and its impacts,
- every modification needs to generate an history entry
> [History] impact api management

- chaos/fields.py
- chaos/history.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/versions/50f90e14e248_history_disruptions.py
- tests/features/deletion-disruption.feature
- tests/features/list-disruption-history.feature
- tests/features/list-disruption-with-impacts-history.feature
- tests/features/steps.py
This PR adds history feature on disruption API
Issue link: BOT-1378
- create an disruption
- edit them
- add or update impacts inside
- request disruption/{id}/history
> Feature bot 1378 disruptions historic reloaded

- chaos/history.py
- tests/features/list-disruption-history.feature
This PR fix the routes absence when getting line_section route_point like on history API
> Hotfix routes line section in history

- chaos/fields.py
- chaos/history.py
- chaos/models.py
This PR is a small tentative to apply PEP8 standards
no regression should occur
You can check what's left to do with http://pep8online.com/ ;)
> Init for some pep8

- chaos/fields.py
This PR fix some pylint and pep8 for fields.py
> Fix some pep8, pylint

- README.md
This PR adds some crucial versions requirements
Read it !
> [doc] crucial requirements

- chaos/utils.py
- requirements.txt
This PR fix the security of CVE-2019-14806 for the library Werkzeug
BOT-1514
> Fix CVE-2019-14806

- chaos/__init__.py
This PR upgrade proto
`git submodule update`
relates to https://github.com/CanalTP/Chaos/pull/398
> [proto] upgrade master

- chaos/fields.py
- chaos/formats.py
- chaos/history.py
- chaos/mapper.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/alembic.ini
- migrations/versions/4e3c651ba4be_add_author_of_disruption.py
- tests/features/disruption-with-author.feature
- tests/features/list-disruption-history.feature
This PR adds author field on disruption
Issue link: BOT-1475
> Adding author field to disruption

- chaos/db_helper.py
- chaos/navitia.py
- tests/features/impacts-with-pt-objects.feature
This PR fix the problem of getting a good answer when trying with a token that doesn't work after using a correct token for a ptobject search in navitia
Issue link: BOT-959
> Update the key cache ptobject navitia search

- chaos/db_helper.py
- tests/features/impacts-with-pt-objects.feature
This PR fix the problem of returning the line info on a line_section who have one of her stop_area unknown by navitia
Issue link: BOT-1505
> Return ptobject error on stoparea of line_section

- chaos/__init__.py
- chaos/navitia.py
- requirements.txt
This PR try to fix the errors of Loop Exit and set in rmq
Issue link: BOT-1616
> Update gevent + indent ?

- chaos/__init__.py
This PR fix the return in log of : 
Issue link: http://bugs.python.org/issue7980
> Fix http://bugs.python.org/issue7980

- chaos/models.py
- chaos/utils.py
- tests/features/deletion-severity.feature
- tests/features/list-severity.feature
- tests/features/update-severity.feature
Orthographic corrector
Read it :book:
> [wording] correction

- chaos/models.py
- impactsExporter.py
This PR fusion channels to simplify the export csv file
Issue link: BOT-1306
> Simplify export csv file

- README.md
- chaos/__init__.py
- chaos/api.py
- chaos/db_helper.py
- chaos/exceptions.py
- chaos/fields.py
- chaos/formats.py
- chaos/logging_utils.py
- chaos/mapper.py
- chaos/models.py
- chaos/navitia.py
- chaos/populate_pb.py
- chaos/resources.py
- chaos/utils.py
This PR upgrade comments
Read it :male_detective:
> Patch upgrade comments copyrights

- chaos/fields.py
- tests/features/disruption-with-impacts_and_depth.feature
This PR fix the issue of displayed size limitation of impacts
Issue link: BOT-1693 (fix)
> Display 20 impacts instead of 10

- chaos/models.py
- chaos/resources.py
- chaos/validate_params.py
- tests/features/create-disruption-with-properties.feature
- tests/features/create-disruption.feature
This PR fixes  creating or editing a disruption with cause of another client
Issue link: BOT-793
> Bugfix when we POST or PUT disruption with cause of another client

- chaos/db_helper.py
- tests/features/create-disruption-with-impacts.feature
- tests/features/create-disruption.feature
- tests/features/impacts-with-pt-objects.feature
- tests/features/update-disruption.feature
This PR add single quote in ptobject not found error message
Issue link: bot-1570
> Add single quote in ptobject not found error message

- chaos/api.py
- chaos/fields.py
- chaos/formats.py
- chaos/mapper.py
- chaos/resources.py
- documentation/swagger.yml
- tests/features/post-contributor.feature
- tests/features/steps.py
This PR  add new route POST contributor
Issue link: BOT-1762
- See swagger file
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/BOT-1762-add-post-contributor/documentation/swagger.yml
> Bot 1762 add post contributor

- chaos/__init__.py
- chaos/api.py
- chaos/default_settings.py
- chaos/exceptions.py
- chaos/new_relic.py
- requirements.txt
This PR update the integration of newrelic on chaos
Issue link: BOT-1204
- `pip install -r requirements.txt`
- Add a newrelic.ini (get it from your newrelic account) file somewhere (accessible by chaos)
- Update the env NEWRELIC_CONFIG_FILE with the path to the newrelic.ini file
- Launch chaos and see that the new app is adding to newrelic
Related to https://github.com/CanalTP/fab_chaos/pull/54
> Newrelic update

- chaos/validate_params.py
- tests/features/create-disruption.feature
This PR fix bug when we post or put a disruption with invalid cause id
Issue link: https://jira.kisio.org/browse/BOT-1795
Create or edit a disruption with invalid cause ID
> #BOT-1795 - Bugfix when we post or put a disruption with invalid cause id

- Dockerfile.dev
This PR fix the docker file in order to create an image for development. 
Issue link: BOT-1756
- Launch the creation of the image (with docker)
- The image should be created without any error
> Update docker dev file

- documentation/swagger.yml
This PR adds documentation
BOT-2021
> Doc explaining Client Contributor

- README.md
This PR adds documentation for some recent Linux distro (Ubuntu20)
> [Doc] Install on recent linux distro

- docker-compose.yml
This PR add regristry ENV_VAR to be able to deploy with jenkins
**Please merge this PR before this one => https://github.com/CanalTP/Chaos/pull/445**
:grey_exclamation: Note : for security reasons, custom configurations (Jenkinsfile & specific ENV_VARS) are in private repositories
> [Docker step1] Deploy thru a jenkinsfile (task bot-2074)

- chaos/navitia.py
- chaos/resources.py
- chaos/utils.py
- tests/features/impacts-with-pt-objects.feature
- tests/navitia_test.py
This PR return a 401 response with the navitia message when the authorization token is not valid for navitia for the corresponding coverage
Issue link: BOT-2083
- Try to post a disruption with an "authorization" that doesn't work
- You should see a 401 response with an error message that comes from navitia
> Return error from authorization navitia

- documentation/swagger.yml
doc:
Application_periods is required for an impact creation.
> Doc: application_periods required for impact creation.

- chaos/populate_pb.py
- tests/populate_pb_test.py
This PR also publishes application period patterns if used while creating/modifying an impact. 
https://jira.kisio.org/browse/NAVITIAII-3277
honcho run nosetests
> Chaos: Publish application period period pattern if present

- chaos/populate_pb.py
- tests/populate_pb_test.py
> Update proto to manage timezone

- chaos/db_mapper/disruption.py
- chaos/fields.py
- chaos/models.py
- chaos/populate_pb.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/versions/2d8031cd6452_add_timezone_in_pattern.py
- tests/features/impacts-with-application_period_patterns.feature
- tests/populate_pb_test.py
This PR add timezone in pattern section
- https://jira.kisio.org/browse/BOT-2401
> Bugfix bot 2401 pattern

- migrations/versions/5bf2d2bc5cb_add_rail_section.py
Remove parent record before removing child records
@kun2985 
@pthegner
> Fix db downgrade issue

- documentation/faq_fr.md
> [Patch Doc] FAQ chaos

- README.md
- documentation/faq_fr.md
Cette FAQ couvre un certain nombre de questions remontées par des integrateurs.
> FAQ fr pour Chaos

- documentation/swagger.yml
This PR change documentation to make blocked_stop_areas minimum 0
Issue link:bot-2694
> [RailSection] DOC blocked_stop_areas minimum 0

- chaos/db_helper.py
- chaos/formats.py
- chaos/mapper.py
- chaos/resources.py
- documentation/swagger.yml
- test.jenkinsfile
- tests/features/create-disruption-with-impacts.feature
- tests/features/impacts-with-pt-objects.feature
- tests/format_test.py
- tests/json_validator_error_test.py
This PR fixes line_section id required but not used bug
Issue link:bot-2500
This is a bug fix 
- create disruption with line_section with or without id should be functional
> Feature bot-2500 line_section id not required

- migrations/versions/4f2a5821f666_add_db_table_indexes.py
This PR adds indexes on db tables in order to improve the performance of OGV1
Issue link: BOT-2782
This is a technical debt
> Add index to improve the performance of OGV1

- tests/features/disruption-with-type.feature
This PR removes code duplication in features/disruption-with-type.feature
> Remove scenario fixture duplication in disruption-with-type.feature

- chaos/db_mapper/disruption.py
- chaos/fields.py
- chaos/formats.py
- chaos/history.py
- chaos/mapper.py
- chaos/models.py
- chaos/resources.py
- documentation/swagger.yml
- migrations/versions/7c54e065a387_add_type_in_disruption.py
- tests/features/disruption-with-type.feature
- tests/features/list-post-disruptions-search.feature
- tests/features/post-impacts-search.feature
This PR add a new type of disruption ("unexpected")
Issue link: BOT-2675
> Add unexpected disruption
