chaos/utils.py
fixing typo in is_published() function call.
=> api: fix a typo in disruption status check

chaos/resources.py
In order to solve the problem exposed in https://github.com/CanalTP/Chaos/issues/189 we call refresh function if the object is used after the commit.
=> api: refresh object after session commit

chaos/publisher.py, chaos/resources.py, chaos/utils.py, tests/disruption_test.py, tests/testing_settings.py
This PR fix an error when the rabbitmq is down -> no perturbation set into navitia
Issue link:
http://jira.canaltp.fr/browse/RZO-301
Make a perturbation on the NMM TR with your rabbitmq down
Check that:
- an error is set on the logfile
- a message is shown on the NMM TR
- your perturbation is not saved on the chaos database.
@kinnou02
=> Bugfix rzo 301 manage return when no publish to rabbitmq

chaos/models.py, tests/features/list-disruptions-by-pt-object.feature, tests/features/list-disruptions-with-pager.feature
This PR fixes bug RZO-334, duplicate in disruptions list when pagination is used
Connect yourself in NMM traffic report,
- go to realtime/disruptions view
- try to display all disruptions available (tou can select 'past' filter to get many disruptions in response, and pagination)
No duplicate must appear in list.
=> No more duplicate in disruptions list

chaos/api.py, chaos/default_settings.py, chaos/fields.py, chaos/utils.py, migrations/versions/d3eacac50a6_.py
This PR lower execution time of disruption list route.
This is only a first step to optimize.
- upgrade DB
- Try to load a disruption list - eg /disruptions?publication_status%5B%5D=past&publication_status%5B%5D=ongoing&start_page=1&items_per_page=10
- The result should be the very same but should be faster
@pthegner @dvdn
=> Optimize disruption list

chaos/navitia.py, chaos/resources.py
This PR fixes a bug when filling Authorization header with other value than raw Navitia token (i.e. Basic MjdY5ODE3YWEtOWExMy00MDZlLThkOTEtMDgwM2NiNWIyOGY0Og==). The Authorization value was forwarded as the HTTP user and not the Authorization header value.
Issue link:
POST a disruption with 
```
Authorization: <your_raw_token>
```
AND 
```
Authorization: Basic base64encode(<your_raw_token>)
```
Result and Navitia request should be the same
=> forward raw authorization header

Dockerfile, Dockerfile.dev, chaos/default_settings.py, docker-compose.yml
This PR adds the ability to build docker images via Chaos embedded, this image is customizable using environment variables:
* SQLALCHEMY_DATABASE_URI
* DEBUG
* NAVITIA_URL
* RABBITMQ_ENABLED
* RABBITMQ_CONNECTION_STRING
* RABBITMQ_EXCHANGE
* PROFILING_ENABLED
```
docker build -t chaos-ws .
docker run -d -e POSTGRES_USER=navitia -e POSTGRES_PASSWORD=navitia -e POSTGRES_DB=chaos --name chaos_db par-vm232.srv.canaltp.fr:5000/chaos-db
docker run -it --rm -e SQLALCHEMY_DATABASE_URI="postgresql://navitia:navitia@database/chaos" --link chaos_db:database -e RABBITMQ_ENABLED=0 chaos-ws sh -c "until nc -z database 5432; do echo -n '.' ; sleep 1 ; done ; python manage.py db upgrade"
docker run -d -e …
```
=> Enable full customization via environment vars

Dockerfile
This PR fixes the random build failure of uwsgi (always happens in Jenkins build job).
For that, we use the navitia/python base image where uwsgi is already compiled
- docker build .
- This command must never fail
@CanalTP/transteam
=> Use navitia/python image to avoid uwsgi compilation failure

chaos/models.py, chaos/resources.py, tests/features/deletion-severity.feature, tests/features/list-severity.feature, tests/features/update-severity.feature
During creation of an disruption, if impact contains wrong severity ID
application throws an NotFound exception and error message is ambiguous.
This PR fix that issue : Explicit message with used severity and Client
IDs would be displayed.
Issue link: rzo-280
This is a bug new feature
- make a HTTP POST request with contains impact with wrong severity ID
- Response code should be 404 with body 
```
{
"error": {
"message": "Unable to find the severty with id "xyz" and client id xzz"
}
}
```
=> Make error message more explicit when severity couldn't be found

chaos/db_helper.py, chaos/fields.py, chaos/resources.py, tests/features/create-cause.feature, tests/features/update-cause.feature, tests/fields_test.py, tests/testing_settings.py
This PR adds wording management in PUT/POST cause if configuration in Traffic report exists (param 'wording' see https://github.com/CanalTP/RealTimeBundle/pull/366 )
Issue link: RZO-462
POST or PUT a cause to chaos with or without 'wording' into cause json
then check which value  arrives into db table /cause/wording
=> Feature rzo 462 wording for cause

chaos/resources.py
This PR fixes an error when an error occurs ^^ after a POST request on /disruptions.
This is just a mistake on error_fields when marshaling response.
I want to mention the fact that if the postgresql database speaks UTF-8 french, then CHAOS explodes on all the psycopg exceptions. (because of encoding) But I don't know who is to be blamed on this.
Thanks.
=> fix: typo when an error occurs after a post request in disruptions api

Dockerfile, chaos/default_settings.py
This PR fixes the dockerfile to use protobuf 2.6 and updates the configuration file to allow overriding cache config by environment variables 
- Build the image
- You should be able to launch TR tests without a redis instance
BOTeam
=> Refacto dockerfile

chaos/models.py, chaos/resources.py, chaos/utils.py, tests/features/traffic_reports.feature, tests/traffic_reports_test.py
This PR addresses performance issues on /traffic_reports API since latest optimizations
This is a performance optimization
- /traffic_reports should act the same way as before but faster
BOT team
=> Use Disruption rather than impact for traffic_reports

chaos/models.py, chaos/resources.py, documentation/disruptions.md, tests/features/list-disruptions-by-pt-object.feature
This PR adds filter on line_section
Issue link: http://jira.canaltp.fr/browse/BOT-42
New feature
- Create some disruptions/impacts on line_sections and lines,
- Call api disruptions with :
filter uri
then filter uri + line_section=true
- Check response and retrieve your related disruptions/impacts
=> Retrieve line_section disruptions

chaos/models.py, chaos/resources.py, documentation/disruptions.md, tests/features/list-disruptions-with-filter-end-publication-dates.feature
This PR adds restriction filters for end publication dates on disruptions API
Issue link:
jira.canaltp.fr/browse/BOT-45
- create various Disruptions with various end publication dates
- call the api disruptions with choosed parameters  end_publication_startfilter_date & OR end_publication_endfilter_date
- check response
Related to https://github.com/CanalTP/RealTimeBundle/pull/383
=> bot-45 End-publication-dates filters

chaos/fields.py, tests/features/list-disruptions-with-pager.feature
This PR fix the display of disruptions -> impacts retrieve must be published
Issue link: BOT-61
- Create a disruption with two impacts
- Delete (archived) one impact
- When you retrieve the list of dsruption, you should see only one impact for this disruption
=> Fix to only retrieve impacts published

chaos/models.py, chaos/resources.py, chaos/utils.py, docker/honcho_launcher.sh, docker/run.sh, migrations/versions/458134a1e5ea_add_indexes_on_line_section.py, tests/features/impacts-with-pt-objects.feature, tests/features/traffic_reports.feature, tests/testing_settings.py, tests/traffic_reports_test.py
This PR tries to optimize a little traffic_reports calls.
On my env, I go from 8s to 2.5s. But not sure it will be the same in production...
Issue link:
This is an attempt for performance improvement
- Try to use traffic_reports, it should be (a little) quicker
- Nothing should be broken
@CanalTP/bot
=> Try optimize traffic reports

chaos/models.py, chaos/resources.py, chaos/utils.py, tests/features/list-impacts-by-pt-object-uri.feature, tests/features/list-impacts-by-pt-object.feature
This PR add the return of line_section objects from URI /impacts in order to show them on the calendar part in NMM
Issue link: BOT-134
- Create an impact with a line_section objects
- Call chaos API /impacts with parameters : uri[]={line_uri_of_line_section}
- You should retrieve the impact
=> Update filter impacts for line_section

chaos/resources.py, chaos/utils.py, tests/features/traffic_reports.feature, tests/traffic_reports_test.py
This PR add a parameter (in body because of the possible length of the value) to filter traffic_report API with ptobject list
Issue link: BOT-503
For testing purpose, use curl command -> exemple : 
```
curl -X GET 'http://ip_chaos/traffic_reports' -H 'Authorization: d967e37e-7078-40ca-9763-efec48e86660' -H 'Content-Type: application/json' -H 'X-Contributors: shortterm.tr_transilien' -H 'X-Customer-id: transilien' -H 'X-Coverage: transilien' -d '{"ptObjectFilter": {"networks": ["network:DUA801"], "lines": ["line:DUA:810801041"]}}'
```
=> Add ptobject filter on traffic reports

chaos/default_settings.py, chaos/navitia.py, chaos/resources.py, tests/features/traffic_reports.feature, tests/testing_settings.py
This PR change the filter on traffic_report to a POST filter
Issue link: BOT-503
- Create disruptions on chaos
- Post to traffic_report API with correct filter : 
```
{"ptObjectFilter": {"networks": ["network:JDR:2"], "lines": ["line:JDR:TGV"]}}
```
=> Update traffic_report call to post

chaos/default_settings.py, chaos/navitia.py, chaos/resources.py, documentation/swagger.yml, tests/features/traffic_reports.feature, tests/testing_settings.py
This PR change the filter on traffic_report to a POST filter
Issue link: BOT-503
- Create disruptions on chaos
- Post to traffic_report API with correct filter : 
```
{"ptObjectFilter": {"networks": ["network:JDR:2"], "lines": ["line:JDR:TGV"]}}
```
=> Feature bot 499 filter on traffic reports

chaos/resources.py, chaos/utils.py, tests/traffic_reports_test.py
This PR fixes the problem of having multiple networks in global view on stop area impact when permission is on one networks
Issue link: BOT-555
=> Add networks filter management

tests/features/create-disruption.feature, tests/features/update-disruption-with-impacts.feature, tests/json_validator_error_test.py
This PR adds tests on data format of disruption  API
Issue link: BOT-536
This is a technical debt
With CI or manually by launching following commands from CLI 
```honcho run lettuce``` and ```honcho run nosetests```
=> Adding tests for requirement properties on disruption API

chaos/models.py, chaos/utils.py, tests/current_time_test.py, tests/features/steps.py, tests/publication_status_test.py, tests/testing_settings.py
This PR fixes difference in Datetime rendered value between a 
- nominal case : disruption/impact values passing via RMQ to Navitia (it doesn't round datetime second value)
- Navitia reinit case : disruption/impact values directly read in Chaos DB (it rounds datetime to closest second)
Issue link: BOT-569
bug fix
- Submit a disruption to Navitia and compare  'created_at' recorded in DB Chaos and 'updated_at' in Navitia
- Stop and restart Navitia to reload disruptions, and compare  'created_at' recorded in DB Chaos and 'updated_at' in Navitia
It should always be the same
=> Format DateTime now to second

chaos/models.py, chaos/resources.py, documentation/swagger.yml, tests/features/list-disruptions-search-post.feature
This PR add category filter to `disruptions/_search` api
Issue link: BOT-788
- create disruptions with different category
- use api  `disruptions/_search` with parameter `cause_category_id` in the POST request
- this should filter the response
Documentation : http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-788-add-filter-on-category/documentation/swagger.yml
=> Add filter on category

documentation/swagger.yml
The given _search example had "start_page":0, when the minimum is 1.
=> disruptions_search_example_start_page_1_instead_0

documentation/swagger.yml
This PR adds a little example for `publication_status`
Issue link: BOT-806
When doing the BOT-806 ticket, we found that it is not very obvious to understand how to use the `publication_status` filter, so I add a little example in the documentation
=> Add example in doc for publication_status

chaos/navitia.py, tests/navitia_test.py
This PR fixes possible Navitia timeouts
Issue link: BOT-791
- simulate numerous disruptions on the same ptObject
- try to display 'dashboard ' page in TR ihm for this client
- it had to display something (instead of blank)
Relates to Navitia upgrade https://github.com/CanalTP/navitia/releases/tag/v2.63.0 disable_disruption feature
=> Add 'disable_disruption' to queries

chaos/db_helper.py, chaos/fields.py, chaos/formats.py, chaos/mapper.py, chaos/models.py, chaos/resources.py, documentation/swagger.yml, migrations/versions/dfe97c5974e3_add_channel_required.py, tests/features/list-channel.feature, tests/features/put-channel.feature, tests/format_test.py
This PR add the required parameter on the channel type, in order to forbidden impact without specific text (not null or empty) for a channel type. 
Issue link: BOT-850
- create or update a channel for a client with the new parameter `required` to `true`
- try to create an impact without this channel
=> Required channels

documentation/swagger.yml
Example for how to use meta in message, like a key / value "subject" / "mail subject".
=> Example_for_meta_in_messages

chaos/formats.py, chaos/models.py, chaos/resources.py, chaos/utils.py, documentation/swagger.yml, tests/features/list-disruptions-search-post.feature
This PR adds ~feature~ documentation filter on impacts
Issue link: BOT-903
- from TR, you can see that Dashboard view is filtered by impacts ongoing / coming. Previously it was by Disruptions
:grey_exclamation: waiting for https://github.com/CanalTP/Chaos/pull/326
=> Feature bot 903 filter on impacts

documentation/swagger.yml
All required fields are now marked with a red star in models.
"wordings" in category, severity
"name" in tag
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/doc_required_update/documentation/swagger.yml
=> doc : Required fields in POST

documentation/swagger.yml
This PR add `routes` parameters to `pt_object_filter`
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/feature-bot-1010-add-routes-filter/documentation/swagger.yml#/Search/post_disruptions__search
Issue link: BOT-1010
=> Update doc swagger

documentation/swagger.yml
This PR add the parameter `application_period` to `/disruptions/_search` API
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-BOT-1015-update-swagger-doc/documentation/swagger.yml#/Search/post_disruptions__search
Issue link: BOT-1015
=> Update swagger doc

chaos/formats.py, chaos/models.py, chaos/resources.py, chaos/utils.py, documentation/swagger.yml, tests/features/list-disruptions-search-post.feature
This PR adds a feature to search impacts precisely by application_period
Issue link: BOT-733
- read official doc
- call /disruptions/_search withi body like i.e
`{
"tag": [],
"start_page": "1",
"items_per_page": 25,
"depth": 2,
"publication_status": [
"past",
"ongoing",
"coming"
],
"line_section": "true",
"application_period": {
"begin": "2018-10-06T00:00:00Z",
"end": "2018-10-06T23:59:59Z"
}
}`
=> Feature bot 733 add application period filter

chaos/models.py
Fix bindparams
`Jan 30 15:27:47 chaos-prd-ws2 chaosws-ws.ctp.prod.canaltp.fr: [Wed Jan 30 15:27:47 2019] [error] [client 10.93.4.1] "bound parameter named %r" % bind.key) Jan 30 15:27:47 chaos-prd-ws2 chaosws-ws.ctp.prod.canaltp.fr: [Wed Jan 30 15:27:47 2019] [error] [client 10.93.4.1] ArgumentError: This text() construct doesn't define a bound parameter named 'uri_like'`
=> Fix uri_like bindparams

documentation/swagger.yml
This PR fix the `s` on the `total_result` entry
=> Fix pager wording

chaos/models.py, chaos/resources.py, chaos/validate_params.py, documentation/swagger.yml, tests/features/create-disruption-with-impacts.feature, tests/features/disruption-with-impacts.feature, tests/features/steps.py
This PR fix the logic behind the send_notifications behavior
Doc : http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/feature-bot-1156-send-notifications-default-false/documentation/swagger.yml
Issue link: BOT-1156
- create a disruption with an impact and test the parameters `send_notifications` and `notification_date`
=> Default send_notifications to False

migrations/versions/463b471b2a9a_update_impact_send_notifications_values.py
This PR fixes a problem with a new checker which verify that impacts with send_notifications field set to true have also a notification_date.
Before this commit https://github.com/CanalTP/Chaos/commit/d3d9fcaef5b6d31be9b2962f8d7e40c67d028ea5, all impacts pushed to chaos without send_notifications field are saved in database with the column send_notifications = TRUE and notification_date = NULL.
So I add a migration file in order to clean the database where "send_notifications" column = true and "notification_date" column is empty.
=> add a migration file in order to fix send_notifications values in database

migrations/versions/463b471b2a9a_update_impact_send_notifications_values.py
This PR fix the migration in order to have a correct history (when send_notifications = true -> manage like a notification even if notification_date is null)
@vpassama , after some brainstorming about your old PR, we have another solution to this problem of notification_date null when send_notifications = true. Could you check it if it's ok with you.
=> [notification_date] Migration to get a value for old impacts

requirements.txt
jinja2 2.10.1 has requirement MarkupSafe>=0.23, but you'll have markupsafe 0.18 which is incompatible.
=> Update requirements.txt for MarkupSafe

documentation/swagger.yml
This PR doc swagger for new history route and a little correction for localization
Issue link: bot-1315
- http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-1315-doc-swagger-route-history/documentation/swagger.yml#/WIP/get_disruptions__id__history
=> Doc swagger for new history route

chaos/api.py, chaos/models.py, chaos/resources.py, documentation/swagger.yml, migrations/versions/cf4581a9123_init_history_schema.py, tests/features/list-disruption-history.feature, tests/features/terrain.py
This add the route /disruptions/{UIID}/history and return a versionnning list of the disruption (just the modification of the disruption -> not the impacts) 
Issue link: BOT-1311
- Create then change the disruption properties (multi-time)
- Call the API with /disruptions/{UIID}/history
- You should see all modification except for the impacts parts
|Given|When|Then|
|---|---|---|
|J'ai créé une perturbation|Je consulte l'historique de cette perturbation|J'ai une liste avec 1 seule entrée, l'état actuel de la perturbation et sa date de création|
|Je modifie la cause de cette perturbation|Je consulte l'historique de cette perturbation|J'ai une liste avec 2 entrées, la première entrée est l'état de création, et la deuxième entrée est …
=> History disruption step 1

chaos/db_helper.py, migrations/versions/d57921a3453_update_carriage_return.py
This PR fix the problem of html messages that was copied from word
Issue link: BOT-1167
- copy from a word doc into an html message of an impact
- get the message from chaos api
- you shouldn't see \r\n in the text return
=> Fix return carriage of html messages

documentation/swagger.yml
This PR adds swagger documentation for disruption history API
Issue link: BOT-1338
=> Updating swagger documentation with disruption history section

chaos/resources.py, tests/features/list-disruption-history.feature
This PR adds disruption id validation for GET history
Issue link: BOT-1403
=> Add disruption id validation for GET history

chaos/resources.py, chaos/utils.py, tests/features/create-cause.feature, tests/features/create-disruption-with-impacts.feature, tests/features/create-disruption.feature, tests/features/create-severity.feature, tests/features/disruption-with-impacts.feature, tests/features/impacts-with-application_period_patterns.feature, tests/features/impacts-with-pt-objects.feature, tests/features/list-post-disruptions-search.feature, tests/features/update-cause.feature, tests/features/update-disruption-with-impacts.feature, tests/features/update-severity.feature, tests/json_validator_error_test.py
This PR change the error message to override the default validator message "[] is too short"
Issue link: bot-749
- POST / PUT disruption and POST / PUT impact with "impacts":[]
- POST / PUT disruption and POST / PUT impact with "objects":[]
- POST / PUT disruption and POST / PUT impact with "application_periods":[]
... (you can use also all array that have this validation : minItems = 1 -> see chaos\formats.py)
=> Add management of empty array error in json validator

chaos/resources.py, chaos/validate_params.py, documentation/swagger.yml, tests/features/list-disruptions-with-pager.feature, tests/features/list-impacts-with-pager.feature, tests/features/list-post-disruptions-search.feature, tests/features/post-impacts-search.feature
This PR limit items_per_page parameter in order to limit the potential excessive usage of the API
Issue link: BOT-839
- Get to API disruptions with parameter items_per_page > 1000
- Post to API disruptions/_search with parameter items_per_page > 1000
- Post to API impacts/_search with parameter items_per_page > 1000
- You should the the error
=> Limit items_per_page parameter

documentation/swagger.yml
This PR updates swagger documentation of author attribute on disruption
Issue link: BOT-1544
=> Update documentation with author attribute of disruption

chaos/__init__.py
This PR fix the error `TypeError: child watchers are only available on the default loop`
=> [Export] bugfix with gevent 1.4

documentation/swagger.yml
This PR update the swagger documentation to use openapi 3
Note:
- it should help also to give a better example of a PUT Disruption with an Impact ID
- a better description of a ptObject type line-section (specific meta object)
Issue link: BOT-1680
check with this address : 
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-1680-openapi-3/documentation/swagger.yml
=> Update swagger 2 to openapi 3

chaos/db_helper.py, tests/features/impacts-with-pt-objects.feature, tests/json_validator_error_test.py
This PR fix the debugger error shown if you try to add an impact of type line_section without line_section entry
Issue link: BOT-1666
- try to create a disruption with an impact who have an object of type line_section and do not add the line_section part
- you should see a return of the API (validation error)
NB : PR https://github.com/CanalTP/Chaos/pull/413 has already an example of a correct line_section impact creation
=> Add line_section validation entry

chaos/models.py, tests/features/disruption-with-author.feature, tests/features/disruption-with-impacts.feature, tests/features/list-disruption-with-properties.feature, tests/features/list-disruptions.feature, tests/features/update-impact.feature
This PR removes archived impacts from disruption get API
Issue link: BOT-1714
=> Task bot 1714 display not archived impacts

requirements.txt
This PR upgrades redis package in order to avoid disconnection issue
Issue link: BOT-1066
=> Upgrade redis package in order to resolve disconnection issue

chaos/models.py, chaos/resources.py, documentation/swagger.yml, tests/features/deletion-severity.feature
This PR fix the problem of deleting severities when they are already linked to impacts.
Updated doc [here](http://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/bugfix-bot-1698-delete-severity/documentation/swagger.yml#/Severity/delete_severities__id_)
Issue link: BOT-1698, BOT-1849
- Create a new severity
- Use it on an impact
- Try to delete the severity
- You should see the error 409
- Delete the impact (or choose another severity for the impact)
- Try to delete the severity
- It should work
=> Manage link to impacts when deleted severities

tests/features/list-post-disruptions-search.feature
This PR fixes error when you follow official documentation on POST disruption/_search ("line-section": true)
```
{
"message": "'bool' object has no attribute 'lower'"
}
```
/!\ Dependency with https://github.com/CanalTP/flask-restful/pull/6
`honcho run lettuce features/list-post-disruptions-search.feature --failfast`
=> [Tests] Different inputs allowed for boolean

documentation/swagger.yml
Removing x-contributors when not required.
Added a specific x-customer-id parameter for when a customer-id can be created through the POST method.
=> DOC: x-contributors and x-customer-id update.

Dockerfile
This PR fixes :
`
app.ERROR: [curl] 55: Send failure: Broken pipe [url] http://172.18.0.3:5000/causes/52c...`
when NMM 'app_test_rt.php' tries to PUT or POST something to container ` chaos-ws`
BOT-2031
=> [docker] patch UWSGI to allow http 'chunked'

Dockerfile
This PR fixes setuptools version to 44.1.0 for python 2.7, to avoid error :
```
...
File "setuptools/__init__.py", line 21, in <module>
import setuptools.version
File "setuptools/version.py", line 1, in <module>
import pkg_resources
File "pkg_resources/__init__.py", line 1380
raise SyntaxError(e) from e
```
=> [Docker] Fixing setuptools version

chaos/models.py, tests/features/post-impacts-search.feature
This PR fixes filter issue on impacts/_search API when ptobject list is empty
Issue link: BOT-2039
=> Fix empty pt object filter on impacts/_search API

chaos/formats.py, chaos/models.py, chaos/resources.py, documentation/swagger.yml, tests/features/list-export.feature
This PR add a sorting system to the exports list
Issue link: BOT-1374
- You should have more than one export done
- When using `/impacts/exports` API, use the sort parameters (see [swagger](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-bot-1374-order-export-list/documentation/swagger.yml#/Export/get_impacts_exports))
- You should see the order change
=> Order export list

documentation/swagger.yml
This PR adds rail_section format example in swagger documentation
ref: bot-2416
You can read the result
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/doc-swagger-rail-section-bot-2416/documentation/swagger.yml
=> [doc] rail_section init

documentation/swagger.yml
This PR adds doc according to rail section mandatory infos
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/patch-doc-railsection-min-mandatory/documentation/swagger.yml#/Impact/post_disruptions__id__impacts
=> [Doc] railsection route_patterns example

documentation/swagger.yml
This PR update swagger file to add rail_section type.
see [here](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task_BOT-2625_rail_section_swagger/documentation/swagger.yml) for the swagger
- https://jira.kisio.org/browse/BOT-2625
This is for a new feature (documentation only)
=> Refs #BOT-2625 - Swagger updated, to add rail_section type.

README.md
This PR explains precisely how to install required version of old protobuf 2.6.1
=> [Doc] Protobuf install

chaos/db_helper.py, chaos/formats.py, chaos/mapper.py, chaos/resources.py, documentation/swagger.yml, tests/features/create-disruption-with-rail-section.feature, tests/format_test.py
This PR makes id not required on rail_section object
Issue link:bot-2773
- create disruption with rail_section with or without id should be functional
=> Make id not required on rail_section object

chaos/db_mapper/disruption.py, chaos/fields.py, chaos/formats.py, chaos/history.py, chaos/mapper.py, chaos/models.py, documentation/swagger.yml, migrations/versions/7c54e065a387_add_type_in_disruption.py, tests/features/disruption-with-type.feature
This PR add the field type to the disruption (used for "unexpected" disruption)
see [swagger](https://petstore.swagger.io/?url=https://raw.githubusercontent.com/CanalTP/Chaos/task-BOT-2802-add-type-to-disruption/documentation/swagger.yml)
Issue link: BOT-2802
=> Add type to disruption
